### ISSUE TITLE
color4b color4f 在lua 里怎么用，有没有 例子或者如何导出文档？

### ISSUE THREAD

**Issue by sishui** [zhongfq/cocos-lua#7]
比如 这个接口
```
Director.instance.setClearColor
```

**Comment by Ander456** [comment]
原来咋用就咋用 静态方法是 点 成员方法是 冒号




| |
安泽豪
游戏开发高级工程师
|
|
闲徕互娱
18610370353
邮箱：18610370353@163.com
|

签名由 网易邮箱大师 定制

在2020年02月01日 13:54，sishui 写道：

比如 这个接口

Director.instance.setClearColor

**Comment by sishui** [comment]
> Director.instance.setClearColor



> 原来咋用就咋用 静态方法是 点 成员方法是 冒号 | | 安泽豪 游戏开发高级工程师 | | 闲徕互娱 18610370353 邮箱：18610370353@163.com | 签名由 网易邮箱大师 定制 在2020年02月01日 13:54，sishui 写道： 比如 这个接口 Director.instance.setClearColor — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

貌似不太对哈 ，比如 Director.instance.setClearColor，按照原来的用法 就应该是 
Director.instance.setClearColor(cc.c4f(0,0,0,0))， 现在貌似没cc.c4f，但我没找到Color4F lua的接口

**Comment by Ander456** [comment]
手边没有电脑 你可以试试直接传入一个table数据看看 不好意思哈




| |
安泽豪
游戏开发高级工程师
|
|
闲徕互娱
18610370353
邮箱：18610370353@163.com
|

签名由 网易邮箱大师 定制

在2020年02月01日 15:54，sishui 写道：

Director.instance.setClearColor

原来咋用就咋用 静态方法是 点 成员方法是 冒号 | | 安泽豪 游戏开发高级工程师 | | 闲徕互娱 18610370353 邮箱：18610370353@163.com | 签名由 网易邮箱大师 定制 在2020年02月01日 13:54，sishui 写道： 比如 这个接口 Director.instance.setClearColor — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

貌似不太对哈 ，比如 Director.instance.setClearColor，按照原来的用法 就应该是
Director.instance.setClearColor(cc.c4f(0,0,0,0))， 现在貌似没cc.c4f，但我没找到Color4F lua的接口

**Comment by sishui** [comment]
去翻了下代码，知道怎么用了
```
Director.instance:setClearColor(0xffffffff)
```
不过这样貌似不太友好

**Comment by zhongfq** [comment]
> 去翻了下代码，知道怎么用了
> 
> ```
> Director.instance:setClearColor(0xffffffff)
> ```
> 
> 不过这样貌似不太友好

个人感觉用0xFFFFFFFF比较友好，与很多其它软件类似，以后可以考虑{r,g,b}的用法

**Comment by sishui** [comment]
> > 去翻了下代码，知道怎么用了
> > ```
> > Director.instance:setClearColor(0xffffffff)
> > ```
> > 
> > 
> > 不过这样貌似不太友好
> 
> 个人感觉用0xFFFFFFFF比较友好，与很多其它软件类似，以后可以考虑{r,g,b}的用法

嗯 ，好的明白了
